from Swordsman import Swordsman
from Archer import Archer
from Mage import Mage
from Boss import Boss

character1 = Swordsman("Royce")
character2 = Archer("Archie")
character3 = Mage("Allister")
boss = Boss("Dhoulmagus Caesar")
print("************************************")
print(f"!----{boss.getUsername()} - HP: {boss.getHp()}----!")
print(f"{character1.getUsername()} - HP: {character1.getHp()}")
print(f"{character2.getUsername()} - HP: {character2.getHp()}")
print(f"{character3.getUsername()} - HP: {character3.getHp()}")
print("************************************")
print("")
boss.slashAttack(character1)
boss.rangedAttack(character2)
character1.basicAttack(boss)
character2.rangedAttack(boss)
character3.magicAttack(boss)
print("")
print("************************************")
print(f"!----{boss.getUsername()} - HP: {boss.getHp()}----!")
print(f"{character1.getUsername()} - HP: {character1.getHp()}")
print(f"{character2.getUsername()} - HP: {character2.getHp()}")
print(f"{character3.getUsername()} - HP: {character3.getHp()}")
print("************************************")
print("")
boss.heal()
boss.magicAttack(character1)
character1.slashAttack(boss)
character2.rangedAttack(boss)
character3.magicAttack(boss)
print("")
print("************************************")
print(f"!----{boss.getUsername()} - HP: {boss.getHp()}----!")
print(f"{character1.getUsername()} - HP: {character1.getHp()}")
print(f"{character2.getUsername()} - HP: {character2.getHp()}")
print(f"{character3.getUsername()} - HP: {character3.getHp()}")
print("************************************")
print("")